### ISSUE TITLE
Issue with css dependency: "process not defined". 

### ISSUE THREAD

**Issue by echobops** [f5/unovis#177]
I'm following the basic Svelte install / demo instructions and have come across an error with one of the depencies (caught in the browser): 

```
emotion-serialize.browser.esm.js:47 Uncaught ReferenceError: process is not defined
    at emotion-serialize.browser.esm.js:47:1
    at main.js:7:2
```

This is from the @emotion/css package. I'm not sure why its trying to access the "process" variable in the browser. I realize this isn't your package, but am not sure where else to post the issue. I'm using:

rollup: ^2.79.1
svelte: ^3.58.0

**Comment by rokotyan** [comment]
@echobops Can you please share more details about your Svelte set up (e.g. are you using SvelteKit)?

**Comment by echobops** [comment]
I am using "uibuilder" (node-red-contrib-uibuilder v6.3.0), an NPM module for Node-red. It built a project for me, which has the following package.json (with some additions there by myself). Normally I'd add @unovis/svelte /ts as dependancies here. 

```
{
  "name": "svelte-basic",
  "description": "A basic Svelte template for uibuilder and Node-RED.",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "rollup -c --environment NODE_ENV:production",
    "dev": "rollup -c -w --environment NODE_ENV:development",
    "start": "sirv public --no-clear"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "locally-unique-id-generator": "^0.1.5",
    "rollup": "^2.79.1",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.58.0"
  },
  "dependencies": {
    "feather-icons": "^4.29.0",
    "lodash": "^4.17.21",
    "luxon": "^3.2.1",
    "navigo": "^8.11.1",
    "sirv-cli": "^2.0.0",
    "svelte-frappe-charts": "^1.10.0",
    "svelte-octicons": "^17.13.0",
    "sveltestrap": "^5.9.0"
  }
}
```

**Comment by rokotyan** [comment]
Thanks @echobops, as a quick test can you please try initializing Unovis's components after the component has been mounted? Here's an example:

```svelte
<script>
  import { onMount } from 'svelte';
  
  ...

  let didMount = false
  onMount(async () => {
    didMount = true
  });
</script>

{#if didMount}
  <VisXYContainer {data}>
    ...
  </VisXYContainer>
{/if}
```

**Comment by rokotyan** [comment]
Closing because of inactivity
